name: Gitflow
on: 
  # To create pull requests.
  - push 

permissions:
  contents: read
  pull-requests: write
  
jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
    - uses: Logerfo/gitflow-action@0.0.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        auto-merge: false # If `true`, will try to automatically merge the pull requests.