name: Check PR

on:
  # WARNING: Make sure to never check out, build or run untrusted code with the 'pull_request_target' event.
  # See: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types: [opened, edited]

jobs:

  check-branches:
    name: Check base branch and branch name
    runs-on: ubuntu-latest
    steps:
      - uses: semestry/git-flow-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}